name: Docker publish

on:
  push:
    branches: [ "master" ]
    # Publish pep440 tags as releases.
    tags: [ '*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Convert repository name to lowercase
        id: set-variables
        run: |
          echo "image=${IMAGE_NAME,,}" >>${GITHUB_OUTPUT}
          # Only enable push on push events (already covered above, but this is a safeguard)
          echo "push=${{ github.event_name != 'pull_request' }}" >>${GITHUB_OUTPUT}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
    outputs:
      image: ${{ steps.set-variables.outputs.image }}
      push: ${{ steps.set-variables.outputs.push }}
      meta-tags: ${{ steps.meta.outputs.tags }}
      meta-labels: ${{ steps.meta.outputs.labels }}

  build:
    needs:
      - prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
        exclude:
          # Only build packages for ARMv6 and ARMv7 for tagged releases
          - platform: ${{ startsWith(github.ref, 'refs/tags/v') && 'nothing' || 'linux/arm/v6' }}
          - platform: ${{ startsWith(github.ref, 'refs/tags/v') && 'nothing' || 'linux/arm/v7' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.platform != 'linux/amd64'
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: needs.prepare.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ needs.prepare.outputs.push == 'true' }}
          platforms: ${{ matrix.platform }}
          build-args: |
            GIT_REPOSITORY=${{ github.repository }}
            "SSH_DEPLOY_KEY=${{ secrets.DOCKER_DEPLOY_KEY }}"
          tags: ${{ needs.prepare.outputs.meta-tags }}
          labels: ${{ needs.prepare.outputs.meta-labels }}
